export enum GameEventServer {
  ERROR = 'SERVER_ERROR',
  CREATE_ROOM = 'SERVER_CREATE_ROOM',
  JOIN_ROOM = 'SERVER_JOIN_ROOM',
  PLAYER_READY = 'SERVER_PLAYER_READY',
  LEAVE_ROOM = 'SERVER_LEAVE_ROOM',
  MOVE_PIECE = 'SERVER_MOVE_PIECE',
}

export enum GameEventClient {
  ERROR = 'CLIENT_ERROR',
  ROOM_INFORMATION = 'CLIENT_ROOM_INFORMATION',
  PLAYER_JOIN_ROOM = 'CLIENT_PLAYER_JOIN_ROOM',
  PLAYER_LEAVE_ROOM = 'CLIENT_PLAYER_LEAVE_ROOM',
  PLAYER_READY = 'CLIENT_PLAYER_READY',
  START_GAME = 'CLIENT_START_GAME',
}
