version: '3'
services:
  nodejs:
    container_name: chinese-chess-server-app-cicd
    build:
      context: .
      dockerfile: Dockerfile
    image: chinese-chess-server-app-cicd
    ports:
      - '3005:${SERVER_PORT}'
      - '8080:${SERVER_SOCKET_PORT}'
